### ISSUE TITLE
AMO description, plus maybe demo URLs in the README here

### ISSUE THREAD

**Issue by grahamperrin** [padenot/up-to-eleven#1]
Hi

Big :heart: for the extension!

At https://github.com/padenot/up-to-eleven#readme maybe include a handful of links to pages where the effects of the extension can be heard. 

Also for https://github.com/padenot/up-to-eleven/blob/master/README.md maybe change the US-specific URL to the one shown below. 

----

From the current one-liner at https://addons.mozilla.org/addon/up-to-eleven/ – 

> Increase the audio on a tab, in case it's not intelligible

– it's not clear whether the extension is also intended for cases where unaltered playback would be **a mixture** of audible (loud enough) and non-intelligible (too quiet). Simply: 

- I understand that the extension will up the volume, but will it also automatically step down when things get too loud?

… then up automatically up again, down and up and so on? Or must I press the button if things become shouty?

Maybe add a plain English description, with a brief (two- or three-point) outline of possible use cases. Keyword _interview_ is probably good :+1: but FWIW I shouldn't make it too specific (no mention of _sports_ interviews, for example). 

----

I tested version 0.1 first with a demo recording (made before I discovered up-to-eleven) during which I intentionally mumbled in conversation with a colleague. The whole thing was quiet; not _a mixture_ of levels. 

Later today I might speed through Mozilla bug [1476253 - Volume post-amplifier for videos with poor sound level](https://bugzilla.mozilla.org/show_bug.cgi?id=1476253) to tell whether any of those examples fit the _mixture_ criterion.

**Comment by padenot** [comment]
Fixed in https://github.com/padenot/up-to-eleven/commit/7435640a00c638b3a5b36c1607b30eb70891aa55
